[[template-layout]]
= Template Layout
Doc Writer <tequlia2pop@gmail.com>
:toc: left
:homepage: http://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#template-layout

[[including-template-fragments]]
== 包含模板片段

[[defining-and-referencing-fragments]]
=== 定义和引用片段

在我们的模板中，我们通常希望包含来自其他模板的部分，如页脚，标题，菜单等部分...

为了做到这一点，Thymeleaf 需要我们定义这些部分，称为“片段”，以便包含，这可以使用 `th:fragment` 属性来完成。

假设我们要为所有杂货店网页添加标准的版权页脚，所以我们创建一个包含下列代码的 `/WEB-INF/templates/footer.html` 文件：

[source,html,indent=0]
[subs="verbatim,quotes"]
----
<!DOCTYPE html>

<html xmlns:th="http://www.thymeleaf.org">

  <body>
  
    <div th:fragment="copy">
      &copy; 2011 The Good Thymes Virtual Grocery
    </div>
  
  </body>
  
</html>
----

上面的代码定义了一个称为 `copy` 的片段，我们通过使用 `th:insert` 或 `th:replace` 属性（也可以使用 `th:include`，尽管从 Thymeleaf 3.0 起不再推荐使用）可以轻松地将它包含在我们的主页中：

[source,html,indent=0]
[subs="verbatim,quotes"]
----
<body>

  ...

  <div th:insert="~{footer :: copy}"></div>
  
</body>
----

注意 `th:insert` 期望接受一个__片段表达式__（`~{...}`），它是__一个生成片段的表达式__。 在上面的例子中，这是一个非复杂的（non-complex）__片段表达式__，（`~{...}`）完全是可选的，所以上面的代码将等价于：

[source,html,indent=0]
[subs="verbatim,quotes"]
----
<body>

  ...

  <div th:insert="footer :: copy"></div>
  
</body>
----

[[fragment-specification-syntax]]
=== 片段的规范语法

__片段表达式__的语法非常简单。有三种不同的格式：

* `"~{templatename::selector}"` 在名为 `templatename` 的模板上应用指定的标记选择器产生一个片段，并将其包含进来。请注意，`selector` 可以是一个片段名称，所以你可以使用 `~{templatename::fragmentname}`，就像在上面的 `~{footer :: copy}`。

====
标记选择器语法由底层的 AttoParser 分析库定义，并且类似于 XPath 表达式或 CSS 选择器。有关详细信息，请参阅 <<appendix-c-markup-selector-syntax>>.
====

* `"~{templatename}"` 包含名为 `templatename` 的完整模板。

====
请注意，在 `th:insert`/`th:replace` 标签中使用的模板名称必须可以由模板引擎当前使用的模板解析器解析。
====

* `"~{::selector}"` 或 `"~{this::selector}"` 包含同一模板中的指定片段。

上述示例中的 `templatename` 和 `selector` 都可以是功能齐全的表达式（甚至是条件表达式！），如：

[source,html,indent=0]
[subs="verbatim,quotes"]
----
<div th:insert="footer :: (${user.isAdmin}? #{footer.admin} : #{footer.normaluser})"></div>
----

再次注意 `th:insert`/`th:replace` 中 `~{...}` 是否是可选的。

片段可以包含所有的 `th:*` 属性。一旦片段被包含在目标模板（具有 `th:insert`/`th:replace` 属性的那个模板）中，这些属性将被计算，并且它们能够引用在该目标模板中定义的所有上下文变量。

====
这种方式对片段来说有一个很大的优点，你可以在一个完全可以被浏览器显示的页面中写入你的片段，它具有完整和__有效__的标记结构，同时 Thymeleaf 可以将它们包含到其他的模板中。
====

[[referencing-fragments-without-thfragment]]
=== 引用没有 th:fragment 的片段

由于标记选择器的强大功能，我们可以包含没有使用 `th:fragment` 属性的片段。 它甚至可以是来自不知道 Thymeleaf 的不同应用程序的标记代码：

[source,html,indent=0]
[subs="verbatim,quotes"]
----
...
<div id="copy-section">
  &copy; 2011 The Good Thymes Virtual Grocery
</div>
...
----

要使用上面的片段，我们可以通过它的 `id` 属性来引用它，类似于 CSS 选择器：

[source,html,indent=0]
[subs="verbatim,quotes"]
----
<body>

  ...

  <div th:insert="~{footer :: #copy-section}"></div>
  
</body>
----

[[difference-between-thinsert-and-threplace-and-thinclude]]
=== th:insert 和 th:replace (以及 th:include) 之间的区别

`th:insert` 和 `th:replace`（以及 `th:include`，自 3.0 以后不推荐）有什么区别？

* `th:insert` 是最简单的：它将简单地插入指定的片段，并将其作为宿主标签的正文。

* `th:replace` 实际上将其宿主标签__替换__为指定的片段。

* `th:include` 类似于 `th:insert`，但是它不是插入片段，它只插入这个片段的内容。

所以像这样的 HTML 片段：

[source,html,indent=0]
[subs="verbatim,quotes"]
----
<footer th:fragment="copy">
  &copy; 2011 The Good Thymes Virtual Grocery
</footer>
----

...在宿主 `<div>` 标签中包含三次，如下所示：

[source,html,indent=0]
[subs="verbatim,quotes"]
----
<body>

  ...

  <div th:insert="footer :: copy"></div>

  <div th:replace="footer :: copy"></div>

  <div th:include="footer :: copy"></div>
  
</body>
----

将产生以下结果：

[source,html,indent=0]
[subs="verbatim,quotes"]
----
<body>

  ...

  <div>
    <footer>
      &copy; 2011 The Good Thymes Virtual Grocery
    </footer>
  </div>

  <footer>
    &copy; 2011 The Good Thymes Virtual Grocery
  </footer>

  <div>
    &copy; 2011 The Good Thymes Virtual Grocery
  </div>
  
</body>
----

== Parameterizable fragment signatures

=== Difference between th:insert and th:replace (and th:include)

== Flexible layouts: beyond mere fragment insertion

== Removing template fragments