[[introducing-thymeleaf]]
= 介绍 Thymeleaf
Doc Writer <tequlia2pop@gmail.com>
:toc: left
:homepage: http://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#introducing-thymeleaf

[[what-is-thymeleaf]]
== Thymeleaf 是什么？
Thymeleaf 是一个现代化的服务器端Java模板引擎，适用于 Web 和独立环境，能够处理 HTML，XML，JavaScript，CSS 甚至纯文本。

Thymeleaf 的主要目标是提供一种优雅和高可维护的方式来创建模板。 为了实现这一点，它建立在__自然模板（Natural Templates）__的概念上，以不影响模板作为设计原型的方式将其逻辑注入到模板文件。 这改善了设计沟通，并弥补了设计和开发团队之间的差距。

从一开始 Thymeleaf 就根据 Web 标准进行设计 - 尤其是 HTML5 - 允许你创建完全验证的模板，如果这是你所需要的。

[[what-kind-of-templates-can-thymeleaf-process]]
== Thymeleaf可以处理什么样的模板？
Thymeleaf支持开箱即用的六种模板，这称为**模板模式（Template Mode）**：

* HTML
* XML
* 文本
* JAVASCRIPT
* CSS
* RAW

有两种__标记__模板模式（HTML和XML），三种__文本__模板模式（TEXT，JAVASCRIPT和CSS）和一种__非操作__模板模式（RAW）。

HTML模板模式允许所有类型的HTML输入，包括HTML5，HTML 4和XHTML。将不执行验证或执行 well-formedness 检查，并且在输出中尽可能地遵守模板代码/结构。

XML模板模式允许XML输入。在这种情况下，代码应该是格式良好的(well-formed) - 没有未闭合的标签，没有未引用的属性等 - 如果发现了违反well-formedness的情况，解析器将抛出异常。请注意，不会执行__验证__（针对DTD或XML Schema）。

TEXT模板模式允许对非标记性质的模板使用特殊的语法。这种模板的示例是文本电子邮件或模板化文档。请注意，HTML或XML模板也可以作为TEXT处理，在这种情况下，它们不会被解析为标记，所有的标签、DOCTYPE、注释等都将被视为纯文本。

JAVASCRIPT模板模式允许在Thymeleaf应用程序中处理JavaScript文件。这意味着能够在JavaScript文件中使用模型数据（与在HTML文件中完成的相同方式），但是使用了特定于JavaScript的集成，例如专门的转义或自然脚本（natural scripting）。 JAVASCRIPT模板模式被认为是__文本__模式，因此使用与TEXT模板模式相同的特殊语法。

CSS模板模式允许处理Thymeleaf应用程序中涉及的CSS文件。与JAVASCRIPT模式类似，CSS模板模式也是—__文本__模式，并使用了TEXT模板模式的特殊处理语法。

RAW模板模式根本不会处理模板。它用于将未处理的资源（文件，URL响应等）插入到正在处理的模板中。例如，HTML格式的外部不受控制的资源可以被包含（include）到应用程序模板中，这是安全的，因为这些资源包含的所有Thymeleaf代码不会被执行。

[[dialects-the-standard-dialect]]
== 方言：标准方言

Thymeleaf是一个极其可扩展的模板引擎（实际上它可以被称为__模板引擎框架__），它允许你定义和自定义你的模板的细节处理方式。

将逻辑应用于标记构件（标签，文本，注释或纯粹的占位符，如果模板是非标记的话）的对象称为__处理器__。**方言**通常由一组这样的处理器组成 - 可能再加上可能一些额外的构件。Thymeleaf的核心库提供了一种开箱即用的方言的方言，称为**标准方言**，这对于大多数用户来说都够用了。

====
注意，方言实际上可以没有处理器，并且完全由其他种类的构件组成，但处理器绝对是最常见的用例。
====

__本教程涵盖标准方言。__您在以下页面中了解的所有的属性和语法功能都由此方言定义，即使没有明确提及。

当然，如果用户想要利用库的高级功能来定义自己的处理逻辑，那么可以创建自己的方言（甚至扩展方言）。 也可以配置Thymeleaf一次使用几种方言。

====
官方的 thymeleaf-spring3 和 thymeleaf-spring4 集成包都定义了一个方言，称为 “SpringStandard Dialect”，它大部分与标准方言相同，但是具有小的适应性，以更好地利用Spring框架中的一些特性（例如，使用 Spring Expression Language 或 SpringEL 而不是 OGNL）。所以如果你是一个Spring MVC用户，你不会浪费你的时间，因为你在这里学习的所有内容都将在你的Spring应用程序中使用。
====

标准方言的大多数处理器都是__属性处理器__。这允许浏览器可以正确地显示HTML模板文件，甚至在被处理之前，因为它们将简单地忽略附加的属性。例如，使用标签库的JSP可以包含不能由浏览器直接显示的代码片段，例如：

[source,jsp]
----
<form:inputText name="userName" value="${user.name}" />
----

... Thymeleaf标准方言将允许我们实现相同的功能：

----
<input type="text" name="userName" value="James Carrot" th:value="${user.name}" />
----

这不仅会被浏览器正确显示，而且还允许我们（可选地）指定一个值属性（在这个例子中是 “James Carrot”），这样当原型在浏览器中静态地打开时也会正确地显示，并且它将被在模板处理期间由 ${user.name} 计算产生的值所替换。

这有助于设计人员和开发人员在同一个模板文件上工作，并减少将静态原型转换为工作模板文件所需的工作量。这是称为__自然模板化（Natural Templating）__的功能。