[[template-layout]]
= Template Layout
Doc Writer <tequlia2pop@gmail.com>
:toc: left
:homepage: http://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#template-layout

[[including-template-fragments]]
== 包含模板片段

[[defining-and-referencing-fragments]]
=== 定义和引用片段

在我们的模板中，我们通常希望包含来自其他模板的部分，如页脚，标题，菜单等部分...

为了做到这一点，Thymeleaf 需要我们定义这些部分，称为“片段”，以便包含，这可以使用 `th:fragment` 属性来完成。

假设我们要为所有杂货店网页添加标准的版权页脚，所以我们创建一个包含下列代码的 `/WEB-INF/templates/footer.html` 文件：

[source,html,indent=0]
[subs="verbatim,quotes"]
----
<!DOCTYPE html>

<html xmlns:th="http://www.thymeleaf.org">

  <body>
  
    <div th:fragment="copy">
      &copy; 2011 The Good Thymes Virtual Grocery
    </div>
  
  </body>
  
</html>
----

上面的代码定义了一个称为 `copy` 的片段，我们通过使用 `th:insert` 或 `th:replace` 属性（也可以使用 `th:include`，尽管从 Thymeleaf 3.0 起不再推荐使用）可以轻松地将它包含在我们的主页中：

[source,html,indent=0]
[subs="verbatim,quotes"]
----
<body>

  ...

  <div th:insert="~{footer :: copy}"></div>
  
</body>
----

注意 `th:insert` 期望接受一个__片段表达式__（`~{...}`），它是__一个生成片段的表达式__。 在上面的例子中，这是一个非复杂的（non-complex）__片段表达式__，（`~{...}`）完全是可选的，所以上面的代码将等价于：

[source,html,indent=0]
[subs="verbatim,quotes"]
----
<body>

  ...

  <div th:insert="footer :: copy"></div>
  
</body>
----

[[fragment-specification-syntax]]
=== 片段的规范语法

__片段表达式__的语法非常简单。有三种不同的格式：

* `"~{templatename::selector}"` 在名为 `templatename` 的模板上应用指定的标记选择器产生一个片段，并将其包含进来。请注意，`selector` 可以是一个片段名称，所以你可以使用 `~{templatename::fragmentname}`，就像在上面的 `~{footer :: copy}`。

====
标记选择器语法由底层的 AttoParser 分析库定义，并且类似于 XPath 表达式或 CSS 选择器。有关详细信息，请参阅 <<appendix-c-markup-selector-syntax>>.
====

* `"~{templatename}"` 包含名为 `templatename` 的完整模板。

====
请注意，在 `th:insert`/`th:replace` 标签中使用的模板名称必须可以由模板引擎当前使用的模板解析器解析。
====

* `"~{::selector}"` 或 `"~{this::selector}"` 包含同一模板中的指定片段。

上述示例中的 `templatename` 和 `selector` 都可以是功能齐全的表达式（甚至是条件表达式！），如：

[source,html,indent=0]
[subs="verbatim,quotes"]
----
<div th:insert="footer :: (${user.isAdmin}? #{footer.admin} : #{footer.normaluser})"></div>
----

再次注意 `th:insert`/`th:replace` 中 `~{...}` 是否是可选的。

片段可以包含所有的 `th:*` 属性。一旦片段被包含在目标模板（具有 `th:insert`/`th:replace` 属性的那个模板）中，这些属性将被计算，并且它们能够引用在该目标模板中定义的所有上下文变量。

====
这种方式对片段来说有一个很大的优点，你可以在一个完全可以被浏览器显示的页面中写入你的片段，它具有完整和__有效__的标记结构，同时 Thymeleaf 可以将它们包含到其他的模板中。
====

[[referencing-fragments-without-thfragment]]
=== 引用没有 th:fragment 的片段

由于标记选择器的强大功能，我们可以包含没有使用 `th:fragment` 属性的片段。 它甚至可以是来自不知道 Thymeleaf 的不同应用程序的标记代码：

[source,html,indent=0]
[subs="verbatim,quotes"]
----
...
<div id="copy-section">
  &copy; 2011 The Good Thymes Virtual Grocery
</div>
...
----

要使用上面的片段，我们可以通过它的 `id` 属性来引用它，类似于 CSS 选择器：

[source,html,indent=0]
[subs="verbatim,quotes"]
----
<body>

  ...

  <div th:insert="~{footer :: #copy-section}"></div>
  
</body>
----

[[difference-between-thinsert-and-threplace-and-thinclude]]
=== th:insert 和 th:replace (以及 th:include) 之间的区别

`th:insert` 和 `th:replace`（以及 `th:include`，自 3.0 以后不推荐）有什么区别？

* `th:insert` 是最简单的：它将简单地插入指定的片段，并将其作为宿主标签的正文。

* `th:replace` 实际上将其宿主标签__替换__为指定的片段。

* `th:include` 类似于 `th:insert`，但是它不是插入片段，它只插入这个片段的内容。

所以像这样的 HTML 片段：

[source,html,indent=0]
[subs="verbatim,quotes"]
----
<footer th:fragment="copy">
  &copy; 2011 The Good Thymes Virtual Grocery
</footer>
----

...在宿主 `<div>` 标签中包含三次，如下所示：

[source,html,indent=0]
[subs="verbatim,quotes"]
----
<body>

  ...

  <div th:insert="footer :: copy"></div>

  <div th:replace="footer :: copy"></div>

  <div th:include="footer :: copy"></div>
  
</body>
----

将产生以下结果：

[source,html,indent=0]
[subs="verbatim,quotes"]
----
<body>

  ...

  <div>
    <footer>
      &copy; 2011 The Good Thymes Virtual Grocery
    </footer>
  </div>

  <footer>
    &copy; 2011 The Good Thymes Virtual Grocery
  </footer>

  <div>
    &copy; 2011 The Good Thymes Virtual Grocery
  </div>
  
</body>
----

== Parameterizable fragment signatures

=== Difference between th:insert and th:replace (and th:include)

== Flexible layouts: beyond mere fragment insertion

[[removing-template-fragments]]
== 删除模板片段

回到示例应用程序，让我们重温一下我们的产品列表模板的最后一个版本：

[source,html,indent=0]
[subs="verbatim,quotes"]
----
<table>
  <tr>
    <th>NAME</th>
    <th>PRICE</th>
    <th>IN STOCK</th>
    <th>COMMENTS</th>
  </tr>
  <tr th:each="prod : ${prods}" th:class="${prodStat.odd}? 'odd'">
    <td th:text="${prod.name}">Onions</td>
    <td th:text="${prod.price}">2.41</td>
    <td th:text="${prod.inStock}? #{true} : #{false}">yes</td>
    <td>
      <span th:text="${#lists.size(prod.comments)}">2</span> comment/s
      <a href="comments.html" 
         th:href="@{/product/comments(prodId=${prod.id})}" 
         th:unless="${#lists.isEmpty(prod.comments)}">view</a>
    </td>
  </tr>
</table>
----

这段代码只是作为一个模板，但作为一个静态页面（当直接打开浏览器而没有经过 Thymeleaf 处理的时候），它不会是一个好的原型。

为什么？ 因为，虽然完全可以由浏览器显示，但是该表只有一行，而这一行有模拟数据。作为一个原型，它只是不会看起来足够真实...我们应该有多个产品，__我们需要更多的行__。

所以让我们添加一些：

[source,html,indent=0]
[subs="verbatim,quotes"]
----
<table>
  <tr>
    <th>NAME</th>
    <th>PRICE</th>
    <th>IN STOCK</th>
    <th>COMMENTS</th>
  </tr>
  <tr th:each="prod : ${prods}" th:class="${prodStat.odd}? 'odd'">
    <td th:text="${prod.name}">Onions</td>
    <td th:text="${prod.price}">2.41</td>
    <td th:text="${prod.inStock}? #{true} : #{false}">yes</td>
    <td>
      <span th:text="${#lists.size(prod.comments)}">2</span> comment/s
      <a href="comments.html" 
         th:href="@{/product/comments(prodId=${prod.id})}" 
         th:unless="${#lists.isEmpty(prod.comments)}">view</a>
    </td>
  </tr>
  <tr class="odd">
    <td>Blue Lettuce</td>
    <td>9.55</td>
    <td>no</td>
    <td>
      <span>0</span> comment/s
    </td>
  </tr>
  <tr>
    <td>Mild Cinnamon</td>
    <td>1.99</td>
    <td>yes</td>
    <td>
      <span>3</span> comment/s
      <a href="comments.html">view</a>
    </td>
  </tr>
</table>
----

好吧，现在我们有三行，这肯定是一个更好的原型。但是...当我们用 Thymeleaf 处理它时会发生什么？

[source,html,indent=0]
[subs="verbatim,quotes"]
----
<table>
  <tr>
    <th>NAME</th>
    <th>PRICE</th>
    <th>IN STOCK</th>
    <th>COMMENTS</th>
  </tr>
  <tr>
    <td>Fresh Sweet Basil</td>
    <td>4.99</td>
    <td>yes</td>
    <td>
      <span>0</span> comment/s
    </td>
  </tr>
  <tr class="odd">
    <td>Italian Tomato</td>
    <td>1.25</td>
    <td>no</td>
    <td>
      <span>2</span> comment/s
      <a href="/gtvg/product/comments?prodId=2">view</a>
    </td>
  </tr>
  <tr>
    <td>Yellow Bell Pepper</td>
    <td>2.50</td>
    <td>yes</td>
    <td>
      <span>0</span> comment/s
    </td>
  </tr>
  <tr class="odd">
    <td>Old Cheddar</td>
    <td>18.75</td>
    <td>yes</td>
    <td>
      <span>1</span> comment/s
      <a href="/gtvg/product/comments?prodId=4">view</a>
    </td>
  </tr>
  <tr class="odd">
    <td>Blue Lettuce</td>
    <td>9.55</td>
    <td>no</td>
    <td>
      <span>0</span> comment/s
    </td>
  </tr>
  <tr>
    <td>Mild Cinnamon</td>
    <td>1.99</td>
    <td>yes</td>
    <td>
      <span>3</span> comment/s
      <a href="comments.html">view</a>
    </td>
  </tr>
</table>
----

最后两行是模拟行！嗯，当然他们是：迭代只应用于第一行，所以 Thymeleaf 没有理由应该删除其他两个。

我们需要一种方法在模板处理期间删除这两行。让我们在第二个和第三个 `<tr>` 标签上使用 `th:remove` 属性：

[source,html,indent=0]
[subs="verbatim,quotes"]
----
<table>
  <tr>
    <th>NAME</th>
    <th>PRICE</th>
    <th>IN STOCK</th>
    <th>COMMENTS</th>
  </tr>
  <tr th:each="prod : ${prods}" th:class="${prodStat.odd}? 'odd'">
    <td th:text="${prod.name}">Onions</td>
    <td th:text="${prod.price}">2.41</td>
    <td th:text="${prod.inStock}? #{true} : #{false}">yes</td>
    <td>
      <span th:text="${#lists.size(prod.comments)}">2</span> comment/s
      <a href="comments.html" 
         th:href="@{/product/comments(prodId=${prod.id})}" 
         th:unless="${#lists.isEmpty(prod.comments)}">view</a>
    </td>
  </tr>
  <tr class="odd" th:remove="all">
    <td>Blue Lettuce</td>
    <td>9.55</td>
    <td>no</td>
    <td>
      <span>0</span> comment/s
    </td>
  </tr>
  <tr th:remove="all">
    <td>Mild Cinnamon</td>
    <td>1.99</td>
    <td>yes</td>
    <td>
      <span>3</span> comment/s
      <a href="comments.html">view</a>
    </td>
  </tr>
</table>
----

一旦处理，一切都会再次看起来是应该的样子：

[source,html,indent=0]
[subs="verbatim,quotes"]
----
<table>
  <tr>
    <th>NAME</th>
    <th>PRICE</th>
    <th>IN STOCK</th>
    <th>COMMENTS</th>
  </tr>
  <tr>
    <td>Fresh Sweet Basil</td>
    <td>4.99</td>
    <td>yes</td>
    <td>
      <span>0</span> comment/s
    </td>
  </tr>
  <tr class="odd">
    <td>Italian Tomato</td>
    <td>1.25</td>
    <td>no</td>
    <td>
      <span>2</span> comment/s
      <a href="/gtvg/product/comments?prodId=2">view</a>
    </td>
  </tr>
  <tr>
    <td>Yellow Bell Pepper</td>
    <td>2.50</td>
    <td>yes</td>
    <td>
      <span>0</span> comment/s
    </td>
  </tr>
  <tr class="odd">
    <td>Old Cheddar</td>
    <td>18.75</td>
    <td>yes</td>
    <td>
      <span>1</span> comment/s
      <a href="/gtvg/product/comments?prodId=4">view</a>
    </td>
  </tr>
</table>
----

属性中的 `all` 这个值是什么意思？`th:remove` 可以以五种不同的方式工作，具体取决于这个值：

* `all`：删除标签及其所有子标签。
* `body`：不要删除包含它的标签，但删除其所有的子标签。
* `tag`：删除包含它的标签，但不要删除其子标签。
* `all-but-first`：删除包含它的标签的所有子标签，除了第一个标签。
* `none`：什么也不做。此值对于动态求值非常有用。

`all-but-first` 这个值有什么用？It will let us save some `th:remove="all"` when prototyping:

[source,html,indent=0]
[subs="verbatim,quotes"]
----
<table>
  <thead>
    <tr>
      <th>NAME</th>
      <th>PRICE</th>
      <th>IN STOCK</th>
      <th>COMMENTS</th>
    </tr>
  </thead>
  <tbody th:remove="all-but-first">
    <tr th:each="prod : ${prods}" th:class="${prodStat.odd}? 'odd'">
      <td th:text="${prod.name}">Onions</td>
      <td th:text="${prod.price}">2.41</td>
      <td th:text="${prod.inStock}? #{true} : #{false}">yes</td>
      <td>
        <span th:text="${#lists.size(prod.comments)}">2</span> comment/s
        <a href="comments.html" 
           th:href="@{/product/comments(prodId=${prod.id})}" 
           th:unless="${#lists.isEmpty(prod.comments)}">view</a>
      </td>
    </tr>
    <tr class="odd">
      <td>Blue Lettuce</td>
      <td>9.55</td>
      <td>no</td>
      <td>
        <span>0</span> comment/s
      </td>
    </tr>
    <tr>
      <td>Mild Cinnamon</td>
      <td>1.99</td>
      <td>yes</td>
      <td>
        <span>3</span> comment/s
        <a href="comments.html">view</a>
      </td>
    </tr>
  </tbody>
</table>
----

`th:remove` 属性可以采用任何 __Thymeleaf 标准表达式（Thymeleaf Standard Expression）__，只要它返回一个允许的字符串值（`all`，`tag`，`body`，`all-but-first` 或 `none`）。

这意味着删除可以是有条件的，如：

[source,html,indent=0]
[subs="verbatim,quotes"]
----
<a href="/something" th:remove="${condition}? tag : none">Link text not to be removed</a>
----

还要注意，`th:remove` 认为 `null` 是 `none` 的同义词，因此以下工作方式与上述示例相同：

[source,html,indent=0]
[subs="verbatim,quotes"]
----
<a href="/something" th:remove="${condition}? tag">Link text not to be removed</a>
----

在这种情况下，如果 `${condition}` 为 false，将返回 `null`，因此不会执行删除。